SwiftCheck/Check.swift
SwiftCheck/Test.swift
SwiftCheckTests/ShrinkSpec.swift

Fixes #29.
In the process I found a bug in the shrinker that prevented SwiftCheck from reporting the number of shrinks it had just performed.  Strange how being the compiler for a while catches these things...

Unroll Shrinking Loop

---

SwiftCheck/Operators.swift
SwiftCheckTests/ShrinkSpec.swift

Fixes bugs where all postconditions evaluate regardless of the precondition.

Make Implication Lazy

---

SwiftCheck/Operators.swift
SwiftCheck/Test.swift

Counterexamples get printed using `toDebugString`. Thus:
- If the type conforms to `DebugPrintable`, `debugDescription` will be evaluated.
- If the type conforms to `Printable`, `description` will be evaluated (as it was before).
- Otherwise, Swift will construct a default string which will probably not be very helpful.
This allows counterexamples to be printed with more detail than regular descriptions might provide.

Debug strings for counterexamples

---

README.md
SwiftCheck/Arbitrary.swift
SwiftCheck/Modifiers.swift
SwiftCheck/Test.swift
SwiftCheckTests/GenSpec.swift
SwiftCheckTests/SimpleSpec.swift
SwiftCheckTests/TestSpec.swift

- Provide a default implementation of `shrink`.
- Finally makes `arbitrary` a static var instead of a method.

Hit 2.0 Hard.

---

.gitignore
SwiftCheck/Modifiers.swift
SwiftCheck/Test.swift
SwiftCheckTests/ModifierSpec.swift

Relaxes the `Hashable` constraint to an `Equatable` one.

Relax IsoOf's Constraints

---

SwiftCheck.xcodeproj/project.pbxproj
SwiftCheck/Arbitrary.swift
SwiftCheck/Property.swift
SwiftCheck/Witness.swift
SwiftCheckTests/GenSpec.swift
SwiftCheckTests/PropertySpec.swift
SwiftCheckTests/ShrinkSpec.swift
SwiftCheckTests/TestSpec.swift

I was tired of having to write `forAllShrink` for so many types over and over again when the library can clearly infer all of that for us given a little bit more information than the usual `Arbitrary`.  Unfortunately, I wasn't able to make this one a sub-protocol of Arbitrary so they can't yet be mixed, but it's still exciting to be able to hide all the boilerplate for once.
For now, the protocol is named `WitnessedArbitrary` and only Functor-esque types of kind `* -> *` can adopt it (because we lack the means to extend tuples).

Add Witnessed Arbitrary Protocol

---

SwiftCheck/Property.swift
SwiftCheck/Test.swift
SwiftCheckTests/TestSpec.swift

I have no idea why this worked the right way the first time around, but it does.  
New behavior for `.verbose` following the discussion in #74.

Print labels in verbose checks

---

SwiftCheck/Arbitrary.swift
SwiftCheck/Gen.swift
SwiftCheck/Property.swift
SwiftCheck/Test.swift

- Removes Boxing in the testing loop
- Converts `Implementation Details` to `MARK: - `s

Details Details

---

Cartfile.resolved
SwiftCheck/Arbitrary.swift
SwiftCheck/Property.swift
SwiftCheck/Test.swift

Straightforward changes except for adding two private functions to emulate the old `lazy` functions.

Update for Xcode 7b6

---

.travis.yml
SwiftCheck.xcodeproj/project.pbxproj
SwiftCheck/Arbitrary.swift
SwiftCheck/Check.swift
SwiftCheck/Modifiers.swift
SwiftCheck/Random.swift
SwiftCheck/Test.swift
SwiftCheck/TestOperators.swift
SwiftCheckTests/DiscardSpec.swift

Per the suggestion in #91, enables the passing of explicit arguments

Publicize Checker Arguments API

---

SwiftCheck/Test.swift

Print the counterexample when a test case throws an error

---

SwiftCheck/Check.swift
SwiftCheck/Test.swift

Instead of merely documenting the defaults, actually provide defaults
for the init arguments. This way clients can just say something like
`CheckerArguments(maxAllowableSuccessfulTests: 200)` and they'll get the
defaults for everything else.

Give CheckerArguments default values

---

SwiftCheck.xcodeproj/xcshareddata/xcschemes/SwiftCheck-iOS.xcscheme

Carthage fails to build the SwiftCheck-iOS target with the error `module 'SwiftCheck' was not compiled for testing`. I believe they best way to fix this is not build the test target for Run & Analyze actions. This is consistent with the configuration on the Mac & watchOS schemes.

Don't build tests on Run & Analyze

---

Sources/Gen.swift
Tests/GenSpec.swift

The first versions of `ap` and `zip` suffered from a bug that caused them not to generate enough entropy by not splitting the RNG and instead distributing it to both generators.  This time, I've re-written the original buggy version with a split instead of two flatMaps which should make calling these common functions an order of magnitude faster since we only have to split once and don't have to create needless inner block invocations with a monadic tower.

Provide more efficient versions of ap and zip

---

Sources/Test.swift
Sources/TestOperators.swift
Tests/PropertySpec.swift

- Fixes a bug where failure expectation and insufficient coverage failures wouldn't print replay values.

Extend Replay Value Printing to All Failure Modes

---

.gitignore
Sources/CoArbitrary.swift
Sources/RawRepresentable+Arbitrary.swift
Sources/WitnessedArbitrary.swift
SwiftCheck.xcodeproj/project.pbxproj
Tests/ComplexSpec.swift
Tests/FailureSpec.swift
Tests/LambdaSpec.swift
Tests/PathSpec.swift
Tests/RawRepresentable+ArbitrarySpec.swift
Tests/ReplaySpec.swift
Tests/RoseSpec.swift

- Adds a default `Arbitrary` implementation for `RawRepresentable` types (i.e. enums).
- Also, minor change to `gitignore` to accommodate convention of putting artifacts in local "build" folder
- Will help users test with enums w/o manually writing generators for all of them.
- How the default implementation is exposed
- Protocol extension (current implementation)
- Struct wrapper, similar to `ArrayOf`, e.g. `RawValuesOf`
- Whether the approach should be extended to other protocols, e.g. `OptionSetType` (which is also `RawRepresentable`, but might deserve its own implementation) …

Default Arbitrary implementation for RawRepresentable types

---

Sources/Gen.swift
Tests/GenSpec.swift
Tests/SimpleSpec.swift

Adds functions `map(_:..._:transform:)` for each `zip` function. Also adds cartesian and monoidal functor tests to `Gen.zip2`
In languages like Swift and Scala, the `liftAN` family of applicative functions are more convenient since currying isn't as convenient as it is in ML or Haskell, where `ap` or `<*>` is more natural. Adding these mapping functions simplifies generating more complex structures such as database models.
There was a gitter conversation that start the discussion on adding monoidal functions to `Gen` because applicative style, not only being inconvenient because of the force of currying, causing the type checker to trip on nested closures.
I'm assuming the …

Add mapping functions for each zip function

---

.travis.yml
README.md
Sources/Modifiers.swift
Tests/SimpleSpec.swift

Swift's lack of implicit conformance and polyvariadic functions makes composing generators using `map`/`zip` or functional operators (`<*>` and `<^>`) cumbersome and/or infeasible for types with a large number of input parameters.  Further, manually gathering many generated values to create a new generator is not only vulnerable to losing entropy\*, but also rife with duplicated calls to [manually split the StdGen](https://gist.github.com/bgerstle/91760b54c0b7dcf1d8fa6cff5cf25765)—not to mention making `Gen(ungen:)` public 🙈. 
This change introduces `GenComposer`, which preserves entropy by encapsulating the logic of splitting the StdGen, as well as offering generic functions to remove even more boilerplate—especially for the …

Add Gen.compose to allow imperative generator composition

---

SwiftCheck.xcodeproj/project.pbxproj
SwiftCheck.xcodeproj/xcshareddata/xcschemes/SwiftCheck-iOS.xcscheme
SwiftCheck.xcodeproj/xcshareddata/xcschemes/SwiftCheck-tvOS.xcscheme
SwiftCheck.xcodeproj/xcshareddata/xcschemes/SwiftCheck.xcscheme

A minimal set of changes to allow support for Swift 2.3
In preparation for the official release of Swift 3.0, merging these changes will afford us the simplest path for support. We will ensure a version of SwiftCheck which works with 2.3 without forking our effort to support 3.0

Swift 2.3 support

---

.gitignore
.travis.yml
Package.swift
Sources/Arbitrary.swift
Tests/RawRepresentableSpec.swift

A quick fix for #174.  Existing conformances for `RawRepresentable` values with `String` and `FloatingPoint` RawValues will need to be made explicit.
It is dangerous to do otherwise.  The implementations for Strings and
FloatingPoint numbers have incredibly poor performance because they
cannot guess the user’s intent.  The String implementation will most
certainly not construct english words that could ever initialize
anything.  The FloatingPoint implementation will never guess the right
combination of bits that will produce the “exact float” - whatever that
could mean - to match the initializer expression.  The search space for integers is tractable, however.

Restrict RawRepresentable extensions to Integers

---

.gitmodules

This submodule was removed but we never cleaned up the gitmodules file. This
resulted in errors when trying to check out the project using Carthage.

Remove gitmodules

---

SwiftCheck.xcodeproj/project.pbxproj

This must be set if we're going to finish up support for Swift 2.3

Fix legacy swift version setting in targets

---

Sources/Check.swift
Sources/Gen.swift
Sources/Property.swift
Sources/Random.swift
Sources/Test.swift
Sources/Testable.swift
Sources/WitnessedArbitrary.swift
Tests/GenSpec.swift
Tests/PropertySpec.swift

Adds some missing features so we can catch up to QuickCheck
- Removes `exhaustive`.  Use `once`.
- Simplifies `Array<T>`'s `Arbitrary` and `WitnessedArbitrary` instances.
- Adds the `again` combinator to complement `once`.
- Adds `Gen.chooseAny` for easy generator construction of `LatticeType`s.
- Fixes a crash that can occur if `UInt64`'s upper bounds are used with a `RandomType` combinator.

Bring our featureset up to par with QuickCheck

---

Tutorial.playground/Contents.swift

Fix typo in documentation markdown

---

SwiftCheck.xcodeproj/project.pbxproj

Disable bitcode for the iOS target.
`SwiftCheck` fails to build with Carthage as `XCTest` is not built with bitcode. Other testing frameworks have also disabled bit code, see Quick PR https://github.com/Quick/Quick/pull/342
n/a
There are no disadvantages to this change. Testing frameworks should not be shipped to the app store and so are not in need of the benefits that come with bit code / app thinning.

Disbale bitcode for Switch-Check-iOS Target

---

Sources/Arbitrary.swift
Sources/Property.swift
Sources/Test.swift
Sources/WitnessedArbitrary.swift

- Use trailing where clauses to cleanup the `forAll` towers.
- Remove many private functions obviated by stdlib changes in Swift 3.0

[NFC] Rearrange Some Things

---

.travis.yml

A change in `iOS_DEVICE_NAME` for Travis configuration: the constant is now `iPad Pro (12.9-inch)`
Without this, the Travis build fails because it doesn't recognize the `iPad Pro (12.9 inch)` target (without a dash).
Are there other things on the Travis configuration that should be changed? I'm not sure about that.

fixed Travis iOS_DEVICE_NAME target

---

.travis.yml
Sources/SwiftCheck/Arbitrary.swift
Sources/SwiftCheck/CoArbitrary.swift
Sources/SwiftCheck/Random.swift

Some small updates to adjust to deprecations between Xcode 9 Beta 4 and Beta 5.
Namely:
- `init(extendingOrTruncating:)` has been renamed `init(truncatingIfNeeded:)`
- `myString.subscript(with:myRange)` is now `String(myString[myRange])`
Resolves #235. Necessary for Xcode 9 Beta 5 support on the `swift-develop` branch.
This is a pretty straightforward change.
None that I am aware of.

Resolves #235: xcode 9 beta 5 deprecation fixes: truncatingIfNeeded + string slicing

---

.travis.yml
Sources/Arbitrary.swift
Sources/Gen.swift
Sources/Lattice.swift
Sources/Modifiers.swift
Sources/Property.swift
Sources/WitnessedArbitrary.swift
SwiftCheck.xcodeproj/project.pbxproj
Tests/SwiftCheckTests/BooleanIdentitySpec.swift
Tests/SwiftCheckTests/PathSpec.swift
Tutorial.playground/Contents.swift

I anticipate this being the last version of Swift 3 that we support before migrating everything to Swift 4.
As Travis has committed to supporting Xcode 9 beta 5, a minor release is currently only blocked on swift.org providing Swift 3.2/4.0 binaries for our Linux build.  I've switched to using a nightly for now.

Migate and update to Swift 3.2

---

SwiftCheck.xcodeproj/project.pbxproj
Templates/CartesianSpec.swift.gyb
Tests/SwiftCheckTests/BooleanIdentitySpec.swift
Tests/SwiftCheckTests/CartesianSpec.swift
Tests/SwiftCheckTests/ComplexSpec.swift
Tests/SwiftCheckTests/DiscardSpec.swift
Tests/SwiftCheckTests/FailureSpec.swift
Tests/SwiftCheckTests/FormatterSpec.swift
Tests/SwiftCheckTests/GenSpec.swift
Tests/SwiftCheckTests/LambdaSpec.swift
Tests/SwiftCheckTests/ModifierSpec.swift
Tests/SwiftCheckTests/PathSpec.swift
Tests/SwiftCheckTests/PropertySpec.swift
Tests/SwiftCheckTests/ReplaySpec.swift
Tests/SwiftCheckTests/RoseSpec.swift
Tests/SwiftCheckTests/ShrinkSpec.swift
Tests/SwiftCheckTests/SimpleSpec.swift
Tests/SwiftCheckTests/TestSpec.swift

I *think* this isn't needed, but the CocoaPods and Carthage builds will be the ultimate determiner.

Switch to built-in SWIFT_PACKAGE flag

---

Sources/SwiftCheck/Random.swift

In `Float.random` and `Double.random` I changed the `^` (bitwise XOR) to `<<` to fix random number generation. I assume the bug comes from Haskell using `^` for exponentiation, see https://hackage.haskell.org/package/random-1.1/docs/src/System-Random.html#line-408 for the Haskell implementation.
It fixes a bug.
I used an explicit type annotation instead of explicitly constructing `Int64`s from integer literals. Happy to change it if that doesn't match the style of the rest of the code. …

Fix random number generation for Float and Double

---

README.md
Sources/SwiftCheck/Arbitrary.swift
Sources/SwiftCheck/Gen.swift
Tests/SwiftCheckTests/GenSpec.swift

This pull requests moves static functions with type constraints on `Gen` into constrained extensions.
This fixes some issues with calls to `fromElements` and `choose`.
Before this PR the following code did not return a `Gen<UInt>`, but a `Gen<Int>`.
```swift
let randomHexValue = Gen<UInt>.choose((0, 15))
```
In addition, it simplifies call sites by not requiring explicit type annotations:
```swift
let uppers : Gen<Character> = Gen<Character>.fromElements(in: "A"..."Z")
```
can now be written as
```swift
let uppers = Gen<Character>.fromElements(in: "A"..."Z")
```
I might have …

Refactor generic static gen functions

---

Sources/SwiftCheck/Cartesian.swift
Sources/SwiftCheck/Gen.swift
Templates/Cartesian.swift.gyb
Templates/CartesianSpec.swift.gyb
Tests/SwiftCheckTests/CartesianSpec.swift
Tests/SwiftCheckTests/GenSpec.swift
Tests/SwiftCheckTests/SimpleSpec.swift

This change does for `zip` what #250 did to `fromElements`, i.e. forces type equality between the `Gen` type and the generic static zip variant.
This fixes the following issues with `zip`:
- `let gen = Gen<Int>.zip(Gen.pure(1), Gen.pure(2))` compiles but unexpectedly returns `Gen<(Int, Int)>`. This will not compile after applying these changes
- `let z = Gen.zip(Gen.pure(1), Gen.pure(2))` did not compile (`Generic parameter 'A' could not be inferred). This will now compile.
This also removes the generic return type from `Gen.map`, instead `map` now always returns `Gen<A>`.
Using …

Refactor zip to ensure type consistency

---

Package.swift

I'm informed that SwiftPM's dependency resolution is not a fan of projects with transitive dependencies that both depend on top-of-tree projects.  Experiment with pinning to a minimum version of FileCheck to see if we can't work that out.

Pin FileCheck To A Version

---

Sources/SwiftCheck/Check.swift
Tests/SwiftCheckTests/SimpleSpec.swift

Passing counter-counterexamples can become visible in verbose output but `counterexample` always assumed its output would only be shown while printing a failing test.  Make it so verbose output reflects what actually happened while processing an example value.

Fix printing passing counter-countexamples in verbose mode

---

Sources/SwiftCheck/Check.swift
Sources/SwiftCheck/Test.swift

#261 requests a way to spell the testing primitives without using the DSL. 
Operators in Swift have a complex and storied history, and their use outside of the standard library is the subject of a lot of styling debates.  Many frameworks that choose to provide custom operators do so because they are trying to mimic a particular syntax or structure.  The trap many fall into is not providing a way out of the DSL.
On the other hand, SwiftCheck's DSL isn't just a matter of syntax.  Tests are data in this framework, and can be …

Provide non-DSL spellings of primitives

---

Tutorial.playground/Contents.swift

This case was changed from `ArrayOf<Int>` to `[Int]`, but the corresponding `getArray` stuck around.
From #264, on this line https://github.com/CodaFi/SwiftCheck/commit/b6b4bc61dc0a41889040a38ebe8f5926ae713d2c#diff-47970fd31917fb63ccf81bd68065f0abR343
Thanks for the hard work on this!
Tutorial fails to run without it:
```
error: Tutorial.playground:339:9: error: value of type '[Int]' has no member 'getArray'
return xs.getArray.filter(f).reduce(true, { $0 && f($1) })
^~ ~~~~~~~~
```
N/A …

Fix Tutorial playground for removal of `ArrayOf<>`

---

Sources/SwiftCheck/Gen.swift

Deprecates the static `map` function for two generator arguments and renames it to `zipWith`.
This was overlooked in d0ac3b949c0f63f05e9de84d91b4424c510c7b7b.
I've noticed that this repository hasn't seen any activity for 3 months. I'd be happy to help in any way I can.

Rename static map to zipWith

---

Sources/SwiftCheck/Gen.swift

This commit fixes a bug where `vary(k, rng)` always returns `rng.split.0` which in turn led to `Gen.variant(seed)` ignoring the `seed` argument.
It fixes a bug.
I haven't written any tests for the changes since it's in a private function. Let me know if you want me to write tests for `Gen.variant` instead.
None that I can think of.

Fix vary function

---

README.md
Sources/SwiftCheck/Gen.swift

Updated references to `one(of:)` that used to be `oneOf`.
Keep the documentation up to date.

Updated references to `one(of:)` in the docs.

---

Sources/SwiftCheck/Property.swift
Tests/SwiftCheckTests/PropertySpec.swift

`Testable.cover` would fail to add coverage labels if the condition was always false, leading to false "sufficient coverage" test results. Take the added regression test in `PropertySpec` as an example:
```
// CHECK-NEXT: +++ OK, failed as expected.
// CHECK-NEXT: *** Insufficient coverage after 100 tests
// CHECK-NEXT: (only {{[0-9]+}}% never, not {{[0-9]+}}%)
property("Cover reports failures for conditions that never happen") <- forAll { (s : Set<Int>) in
let somethingHappened = false
return (s.count == [Int](s).count).cover(somethingHappened, percentage: 1, label: "something happened")
}.expectFailure
```
The expected failure never occurs because `somethingHappened` is always `false` and, as a result, the `"something happened" …

Fix false positives caused by cover conditions that are never true

---

README.md
Sources/SwiftCheck/Test.swift

Thank you for the useful library!
replace `reverse` to `reversed` to fix compile error when referreing to readme
Keep the documentation up to date.

Updated references to `reverse` in the docs

---

Package.swift

This updates swift tools version to 5.2.
This fixes #296. Without this fix, Xcode (from 11.4 and above) will resolve all the test dependencies of SwiftCheck as well: FileCheck.
This prevents Xcode from building previews for SwiftUI, essentially making SwiftUI unusable.
Swift Packages section of [release note for Xcode 11.4](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes):
> Remote Swift packages with tools version 5.2 and above no longer resolve package dependencies that are only used in their test targets, improving performance and reducing the chance of dependency version conflicts. (56925017)
What's worth discussing about this pull …

Update swift tools version to 5.2

---

SwiftCheck.xcodeproj/project.pbxproj

Added XCTest to "Frameworks & Libraries" in iOS and tvOS targets
To fix build issues with Xcode 12.5
I also updated the deployment target to iOS 9.0 as 8.0 is not supported any more.
N/A

fixed Xcode 12.5 build issues
