typelift/SwiftCheck

README.md, SwiftCheck-iOS.xcodeproj/project.pbxproj, SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck/Arbitrary.swift, SwiftCheck/Check.swift, SwiftCheck/Property.swift, SwiftCheck/Test.swift, SwiftCheck/Testable.swift, SwiftCheckTests/DiscardSpec.swift, SwiftCheckTests/PrimeSpec.swift, SwiftCheckTests/SimpleSpec.swift
Update to the new syntax in #4.  Will have to see what I can do about getting things like file and line numbers implicitly.  Swift doesn't seem to like default args in subscript declarations.
=> The rejiggering

.gitmodules, Cartfile.private, Cartfile.resolved, README.md, SwiftCheck-iOS.xcodeproj/project.pbxproj, SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck/Arbitrary.swift, SwiftCheck/Check.swift, SwiftCheck/Combinators.swift, SwiftCheck/Gen.swift, SwiftCheck/Property.swift, SwiftCheck/Random.swift, SwiftCheck/Rose.swift, SwiftCheck/State.swift, SwiftCheck/Test.swift, SwiftCheck/Testable.swift, SwiftCheckTests/DiscardSpec.swift, SwiftCheckTests/PrimeSpec.swift, SwiftCheckTests/SimpleSpec.swift
=> Migrate to Swiftz

.gitignore, Cartfile.private, Cartfile.resolved, README.md, SwiftCheck-iOS.xcodeproj/project.pbxproj, SwiftCheck-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata, SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck.xcworkspace/contents.xcworkspacedata, SwiftCheck/Arbitrary.swift, SwiftCheck/Check.swift, SwiftCheck/Combinators.swift, SwiftCheck/Gen.swift, SwiftCheck/Lattice.swift, SwiftCheck/Modifiers.swift, SwiftCheck/Operators.swift, SwiftCheck/Property.swift, SwiftCheck/Random.swift, SwiftCheck/Rose.swift, SwiftCheck/Test.swift, SwiftCheck/Testable.swift, SwiftCheckTests/BooleanIdentitySpec.swift, SwiftCheckTests/DiscardSpec.swift, SwiftCheckTests/ModifierSpec.swift, SwiftCheckTests/PrimeSpec.swift, SwiftCheckTests/SimpleSpec.swift
:warning: Do not merge until Travis gets its act together. :warning:
=> Swift 1 dot 2

SwiftCheck/Combinators.swift, SwiftCheck/Gen.swift, SwiftCheckTests/GenSpec.swift
=> Gen.weighted

SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck/Arbitrary.swift, SwiftCheck/Combinators.swift, SwiftCheck/Equatable.swift, SwiftCheck/Modifiers.swift, SwiftCheck/Test.swift
Speeds up compilation rather dramatically by careful annotation and denormalization.
=> Faster compiles

SwiftCheck/Arbitrary.swift, SwiftCheck/Modifiers.swift, SwiftCheckTests/ModifierSpec.swift, SwiftCheckTests/ShrinkSpec.swift
- Adds `DictionaryOf` and `SetOf` modifiers.
- Adds a getter for `ContiguousArray`s to `ArrayOf`.
That dictionary generator... so inefficient because `Array.shrink` continues to be a problem.
=> New Modifiers

LICENSE
=> Licensed to Ill

SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck/Arbitrary.swift, SwiftCheck/Gen.swift, SwiftCheck/Lattice.swift, SwiftCheck/Modifiers.swift, SwiftCheck/Property.swift, SwiftCheck/Random.swift, SwiftCheck/Test.swift, SwiftCheckTests/TestSpec.swift
Converts some modifiers to direct instances of `Arbitrary` for future beta where we can get `Arbitrary` fo' real.
=> Support Swift 2.0 beta 2

SwiftCheck/Modifiers.swift, SwiftCheckTests/ModifierSpec.swift
- Makes testing the Focus library substantially easier.  [I'm not entirely sure what other benefits this might have, but it's nice to have invertible functions all the same].
=> Add IsoOf Modifier

SwiftCheck/Arbitrary.swift, SwiftCheck/Gen.swift, SwiftCheck/Property.swift, SwiftCheck/Test.swift
=> Update to that new Swift thing

SwiftCheck/Arbitrary.swift
Fixes for both the numbers and for Bool.
=> Fix Arbitrary signs

SwiftCheck/Arbitrary.swift
=> Integrate changes from TabletopAssistant/arbitrary-sign

SwiftCheck/Test.swift
=> Fix pluralization in doneTesting

SwiftCheck.podspec
Adds CocoaPod support to master.
=> Podiatrism

README.md, SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck/Gen.swift, SwiftCheck/Random.swift, SwiftCheckTests/ComplexSpec.swift, SwiftCheckTests/GenSpec.swift
Fixes #84 and #85.
I've decided to include these as part of the test suite (because you're right, they are very valuable) and link to them in the README as further reading.
=> Gen and Tonic

Cartfile.resolved, SwiftCheck.podspec
In order to make the merge into master this branch begins a feature freeze on `swift-develop`.  The last thing I will be adding for now is the ability to use Cocoapods with 2.0.
=> Final Updates

SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck/Test.swift, SwiftCheckTests/FailureSpec.swift, SwiftCheckTests/GenSpec.swift
Fixes #47 
@robrix You got a favorite tautology you want me to negate in here?
=> Test Failure

SwiftCheck/Test.swift, SwiftCheckTests/TestSpec.swift
Partial fixes for #106 and #107
=> Add forAllNoShrink

SwiftCheck/Test.swift, SwiftCheckTests/FailureSpec.swift, SwiftCheckTests/PropertySpec.swift
=> Catch Exceptions in Tests

SwiftCheck/Gen.swift, SwiftCheck/TestOperators.swift, SwiftCheckTests/BooleanIdentitySpec.swift, SwiftCheckTests/ComplexSpec.swift, SwiftCheckTests/DiscardSpec.swift, SwiftCheckTests/FailureSpec.swift, SwiftCheckTests/GenSpec.swift, SwiftCheckTests/ModifierSpec.swift, SwiftCheckTests/PropertySpec.swift, SwiftCheckTests/ShrinkSpec.swift, SwiftCheckTests/SimpleSpec.swift, SwiftCheckTests/TestSpec.swift, Tutorial.playground/Contents.swift, Tutorial.playground/contents.xcplayground
- Adds more tests to Gen
- `@exported` XCTest so everyone can get rid of that stupid import.
=> Stress-Test Gen

SwiftCheck/Test.swift
Partial fix for problem reported in #116.
=> Shut Existentials Up

SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck/Modifiers.swift, SwiftCheckTests/ModifierSpec.swift, Tutorial.playground/Contents.swift
Fixes #56 and a few retain cycles in arrow gen.
=> Add PointerOf Modifier

SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck/Arbitrary.swift, SwiftCheck/Gen.swift, SwiftCheck/Random.swift, SwiftCheck/Test.swift
=> Make Double Gen More Robust

SwiftCheck.podspec
=> Bump Podspec Version

README.md, Tutorial.playground/Contents.swift
=> Spruce Up The Tutorial

.travis.yml, SwiftCheck/Random.swift
=> Add the shunts

SwiftCheck.podspec, script/cibuild
=> Bump podspec

README.md, Sources/Test.swift, Sources/TestOperators.swift
- Fixes a broken link in the README
- Minor cosmetic code nitpicks that should have been included in the last pull request
- `====` doesn't squish its arguments together.
=> Aesthetics

Sources/Gen.swift, Tests/GenSpec.swift, Tests/RawRepresentableSpec.swift, Tests/SimpleSpec.swift
- Implements zip overloads up to 10 arguments.
=> Implement Monoidal Functor Instance for Gen

.travis.yml, Package.swift, SwiftCheck.xcodeproj/project.pbxproj, Tests/LinuxMain.swift, Tests/SwiftCheckTests/BooleanIdentitySpec.swift, Tests/SwiftCheckTests/ComplexSpec.swift, Tests/SwiftCheckTests/DiscardSpec.swift, Tests/SwiftCheckTests/FailureSpec.swift, Tests/SwiftCheckTests/GenSpec.swift, Tests/SwiftCheckTests/LambdaSpec.swift, Tests/SwiftCheckTests/ModifierSpec.swift, Tests/SwiftCheckTests/PathSpec.swift, Tests/SwiftCheckTests/PropertySpec.swift, Tests/SwiftCheckTests/RawRepresentableSpec.swift, Tests/SwiftCheckTests/ReplaySpec.swift, Tests/SwiftCheckTests/RoseSpec.swift, Tests/SwiftCheckTests/ShrinkSpec.swift, Tests/SwiftCheckTests/SimpleSpec.swift, Tests/SwiftCheckTests/TestSpec.swift
Gets the test suite up and running on Linux - hopefully.  There isn't much documentation around these kinds of things.
=> Try testing on linux

Package.swift
Fixes #195.  I will put out version 0.7.1 because of this.
=> Apparently you don't need testing targets.

Sources/Arbitrary.swift, Tests/SwiftCheckTests/BooleanIdentitySpec.swift, Tests/SwiftCheckTests/ShrinkSpec.swift
=> Tone down the FloatingPoint shrinkers

Sources/Modifiers.swift, SwiftCheck.xcodeproj/project.pbxproj, Tests/SwiftCheckTests/FormatterSpec.swift
=> Remove dependence on self in ArrowOf and IsoOf

.travis.yml, SwiftCheck.xcodeproj/project.pbxproj, Tests/SwiftCheckTests/BooleanIdentitySpec.swift, Tests/SwiftCheckTests/ComplexSpec.swift, Tests/SwiftCheckTests/DiscardSpec.swift, Tests/SwiftCheckTests/FileCheck.swift, Tests/SwiftCheckTests/FormatterSpec.swift, Tests/SwiftCheckTests/GenSpec.swift, Tests/SwiftCheckTests/LambdaSpec.swift, Tests/SwiftCheckTests/ModifierSpec.swift, Tests/SwiftCheckTests/PathSpec.swift, Tests/SwiftCheckTests/PropertySpec.swift, Tests/SwiftCheckTests/ShrinkSpec.swift, Tests/SwiftCheckTests/SimpleSpec.swift, Tests/SwiftCheckTests/TestSpec.swift
Resolves #192 
Deterministic printed output is an important goal of this framework.  It will also keep our test log much cleaner.
=> Use FileCheck to test printed output

Sources/Random.swift
Squashes #205 in a manner that I'm tremendously disappointed with.
=> Plug a hole in some math on very large integers

SwiftCheck.podspec
=> Bump the podspec version

.travis.yml, Sources/Arbitrary.swift, Sources/Cartesian.swift, Sources/Check.swift, Sources/CoArbitrary.swift, Sources/Gen.swift, Sources/Modifiers.swift, Sources/Property.swift, Sources/Random.swift, Sources/Test.swift, Sources/WitnessedArbitrary.swift, Templates/Cartesian.swift.gyb, Tests/SwiftCheckTests/ComplexSpec.swift, Tests/SwiftCheckTests/FormatterSpec.swift, Tests/SwiftCheckTests/GenSpec.swift, Tests/SwiftCheckTests/ModifierSpec.swift, Tests/SwiftCheckTests/PathSpec.swift, Tests/SwiftCheckTests/ReplaySpec.swift, Tests/SwiftCheckTests/RoseSpec.swift, Tests/SwiftCheckTests/SimpleSpec.swift, Tests/SwiftCheckTests/TestSpec.swift
Update to Swift 4.0.  The Linux build is the only one I expect to even run, let alone compile.
=> [WIP] Update to Swift 4.0

Package.resolved, Package.swift
Package.swift now points to typelift Operadics repo
=> Point Package.swift to official deps

Sources/Random.swift
I added a comment to `StdGen.next`:
// P. L'Ecuyer, ``Efficient and Portable Combined Random Number Generators'', Communications of the ACM, 31 (1988), 742--749 and 774.
// https://www.iro.umontreal.ca/~lecuyer/myftp/papers/cacm88.pdf
1. Credit where it's due.
2. For anyone who wants to understand the science behind this RNG.
Nothing.
None.
=> credit the creator of the RNG

Tutorial.playground/Contents.swift
Use the trailing closure syntax in the Tutorial Playground.
Improve the readability of the Tutorial.
Do you think it's better to use this syntax?
I don't see any.
=> Use the trailing closure syntax

Sources/SwiftCheck/Check.swift, Sources/SwiftCheck/Compose.swift, Sources/SwiftCheck/Gen.swift, Sources/SwiftCheck/Property.swift, Sources/SwiftCheck/Random.swift, Sources/SwiftCheck/Rose.swift, Sources/SwiftCheck/Testable.swift, Sources/SwiftCheck/Witness.swift, Tests/SwiftCheckTests/LambdaSpec.swift, Tutorial.playground/Contents.swift
- Documentation updates and modernizations
=> Cleanup crew

README.md
Some brief cleanup before release.
=> Update to Swift 4 package def

Cartfile.resolved, Sources/SwiftCheck/Arbitrary.swift, Sources/SwiftCheck/CoArbitrary.swift, Sources/SwiftCheck/Property.swift, Tests/SwiftCheckTests/ComplexSpec.swift
Silence some warnings introduced by Xcode 9.1's copy of stdlib
=> Update for Xcode 9.1

Package.swift
FileCheck has transferred ownership to a different org.
=> Formalize re-org

SwiftCheck.podspec
Updates the version in **SwiftCheck.podspec**
Currently CocoaPods users can't install the latest version without specifying commit.
After merging the new version should be uploaded to CocoaPods.
=> Bump version in .posdpec

Sources/SwiftCheck/Arbitrary.swift, Sources/SwiftCheck/Lattice.swift, Sources/SwiftCheck/Modifiers.swift, Sources/SwiftCheck/Property.swift, Sources/SwiftCheck/Random.swift, Sources/SwiftCheck/Test.swift, Sources/SwiftCheck/WitnessedArbitrary.swift, SwiftCheck.xcodeproj/project.pbxproj, SwiftCheck.xcodeproj/xcshareddata/xcschemes/SwiftCheck-iOS.xcscheme, SwiftCheck.xcodeproj/xcshareddata/xcschemes/SwiftCheck-tvOS.xcscheme, SwiftCheck.xcodeproj/xcshareddata/xcschemes/SwiftCheck.xcscheme
Cull some unneeded primitives and make the non-user-facing documentation a bit more consistent.  The behavior of some scalar shrinkers could possibly change under this patch but the end results should stay the same.
=> [NFCI] Cosmetic Improvements
